// debug

export const DEBUG = process.env.NODE_ENV === "development";

// accounts

export const GET_LOCAL_CREDENTIALS = "GET_LOCAL_CREDENTIALS";
export const GET_LOCAL_CREDENTIALS_SUCCESS = "GET_LOCAL_CREDENTIALS_SUCCESS";
export const GET_LOCAL_CREDENTIALS_FAIL = "GET_LOCAL_CREDENTIALS_FAIL";

export const CLEAR_LOGIN_USERNAME = "CLEAR_LOGIN_USERNAME";
export const CLEAR_LOGIN_PASSWORD = "CLEAR_LOGIN_PASSWORD";

export const CHANGE_LOGIN_USERNAME = "CHANGE_LOGIN_USERNAME";
export const CHANGE_LOGIN_PASSWORD = "CHANGE_LOGIN_PASSWORD";

export const REQUEST_LOGIN = "REQUEST_LOGIN";
export const REQUEST_LOGIN_SUCCESS = "REQUEST_LOGIN_SUCCESS";
export const REQUEST_LOGIN_FAIL = "REQUEST_LOGIN_FAIL";

// localStorage key

export const LOCAL_STORAGE_USERNAME_KEY = "sc_username";
export const LOCAL_STORAGE_USER_PROFILE = "sc_profile";

// app network

export const APP_OFFLINE = "APP_OFFLINE";
export const APP_ONLINE = "APP_ONLINE";

// database
export const DB_CONNECTING = "DB_CONNECTING";
export const DB_CONNECTED = "DB_CONNECTED";
export const DB_DISCONNECTED = "DB_DISCONNECTED";
export const DB_CONNECTION_CHANGE = "DB_CONNECTION_CHANGE";

export const DB_COLLECTION_CHANGE = "DB_COLLECTION_CHANGE"; // include doc insert/update/delete.. of docs on this collection
export const DB_DOCUMENT_INSERT = "DB_DOCUMENT_INSERT";
export const DB_DOCUMENT_DELETE = "DB_DOCUMENT_DELETE";
export const DB_DOCUMENT_UPDATE = "DB_DOCUMENT_UPDATE";

// database collections
export const DB_COLLECTION_OF_REPO = "repos";
export const DB_COLLECTION_OF_OWNER = "owners";
export const DB_COLLECTION_OF_TAG = "tags";
export const DB_COLLECTION_OF_CATEGORY = "categories";
export const DB_COLLECTION_OF_ME = "me";

// real-time repos lists sync with rxdb
export const UPDATE_REPOS_LIST = "UPDATE_REPOS_LIST";
export const UPDATE_REPOS_LIST_SUCCESS = "UPDATE_REPOS_LIST_SUCCESS";
export const UPDATE_REPOS_LIST_FAIL = "UPDATE_REPOS_LIST_FAIL";

// fetch repos from server
export const FETCH_REPOS_LIST = "FETCH_REPOS_LIST";
export const FETCH_REPOS_LIST_SUCCESS = "FETCH_REPOS_LIST_SUCCESS";
export const FETCH_REPOS_LIST_FAIL = "FETCH_REPOS_LIST_FAIL";

// clear repos increase num after using it
export const CLEAR_INCREASE_PROP = "CLEAR_INCREASE_PROP";

// get languages for group menu
export const QUERY_LANGUAGES_LIST = "QUERY_LANGUAGES_LIST";
export const QUERY_LANGUAGES_LIST_SUCCESS = "QUERY_LANGUAGES_LIST_SUCCESS";
export const QUERY_LANGUAGES_LIST_FAIL = "QUERY_LANGUAGES_LIST_FAIL";

// get categories for group menu
export const QUERY_CATEGORIES_LIST = "QUERY_CATEGORIES_LIST";
export const QUERY_CATEGORIES_LIST_SUCCESS = "QUERY_CATEGORIES_LIST_SUCCESS";
export const QUERY_CATEGORIES_LIST_FAIL = "QUERY_CATEGORIES_LIST_FAIL";

// search/order/filter/group
export const UPDATE_SEARCH_CONDITION = "UPDATE_SEARCH_CONDITION";
export const UPDATE_ORDER_CONDITION = "UPDATE_ORDER_CONDITION";
export const UPDATE_FILTER_CONDITION = "UPDATE_FILTER_CONDITION";
export const UPDATE_GROUP_CONDITION = "UPDATE_GROUP_CONDITION";

// get repos for repos list
export const QUERY_REPOS_LIST = "QUERY_REPOS_LIST";
export const QUERY_REPOS_LIST_SUCCESS = "QUERY_REPOS_LIST_SUCCESS";
export const QUERY_REPOS_LIST_FAIL = "QUERY_REPOS_LIST_FAIL";

export const REPLACE_REPOS_LIST_ITEM = "REPLACE_REPOS_LIST_ITEM";

// filter types
export const FILTER_OPTION_NONE = "FILTER_OPTION_NONE";
export const FILTER_OPTION_HAS_FLAG = "FILTER_OPTION_HAS_FLAG";
export const FILTER_OPTION_HAS_NOTE = "FILTER_OPTION_HAS_NOTE";
export const FILTER_OPTION_UNREAD = "FILTER_OPTION_UNREAD";

// order types

export const ORDER_DESC = "ORDER_DESC";
export const ORDER_ASC = "ORDER_ASC";

// query profile
export const QUERY_MY_PROFILE = "QUERY_MY_PROFILE";
export const QUERY_MY_PROFILE_SUCCESS = "QUERY_MY_PROFILE_SUCCESS";
export const QUERY_MY_PROFILE_FAIL = "QUERY_MY_PROFILE_FAIL";

// add a custom category
export const ADD_CUSTOM_CATEGORY = "ADD_CUSTOM_CATEGORY";
export const ADD_CUSTOM_CATEGORY_SUCCESS = "ADD_CUSTOM_CATEGORY_SUCCESS";
export const ADD_CUSTOM_CATEGORY_FAIL = "ADD_CUSTOM_CATEGORY_FAIL";

// delete a custom category
export const DELETE_CUSTOM_CATEGORY = "DELETE_CUSTOM_CATEGORY";
export const DELETE_CUSTOM_CATEGORY_SUCCESS = "DELETE_CUSTOM_CATEGORY_SUCCESS";
export const DELETE_CUSTOM_CATEGORY_FAIL = "DELETE_CUSTOM_CATEGORY_FAIL";

// attach a category to a repo
export const ATTACH_CUSTOM_CATEGORY = "ATTACH_CUSTOM_CATEGORY";
export const ATTACH_CUSTOM_CATEGORY_SUCCESS = "ATTACH_CUSTOM_CATEGORY_SUCCESS";
export const ATTACH_CUSTOM_CATEGORY_FAIL = "ATTACH_CUSTOM_CATEGORY_FAIL";

// detach a category on a repo
export const DETACH_CUSTOM_CATEGORY = "DETACH_CUSTOM_CATEGORY";
export const DETACH_CUSTOM_CATEGORY_SUCCESS = "DETACH_CUSTOM_CATEGORY_SUCCESS";
export const DETACH_CUSTOM_CATEGORY_FAIL = "DETACH_CUSTOM_CATEGORY_FAIL";

// a repo
export const SELECT_ONE_REPO = "SELECT_ONE_REPO";
// export const SELECT_ONE_REPO_SUCCESS = 'SELECT_ONE_REPO_SUCCESS'
// export const SELECT_ONE_REPO_FAIL = 'SELECT_ONE_REPO_FAIL'

export const RATE_ONE_REPO = "RATE_ONE_REPO";
export const RATE_ONE_REPO_SUCCESS = "RATE_ONE_REPO_SUCCESS";
export const RATE_ONE_REPO_FAIL = "RATE_ONE_REPO_FAIL";

export const STAR_STARCABINET = "STAR_STARCABINET";
export const STAR_STARCABINET_SUCCESS = "STAR_STARCABINET_SUCCESS";
export const STAR_STARCABINET_FAIL = "STAR_STARCABINET_FAIL";

export const ADD_TAG_FOR_REPO = "ADD_TAG_FOR_REPO";
export const ADD_TAG_FOR_REPO_SUCCESS = "ADD_TAG_FOR_REPO_SUCCESS";
export const ADD_TAG_FOR_REPO_FAIL = "ADD_TAG_FOR_REPO_FAIL";

export const REMOVE_TAG_FOR_REPO = "REMOVE_TAG_FOR_REPO";
export const REMOVE_TAG_FOR_REPO_SUCCESS = "REMOVE_TAG_FOR_REPO_SUCCESS";
export const REMOVE_TAG_FOR_REPO_FAIL = "REMOVE_TAG_FOR_REPO_FAIL";

export const QUERY_REPO_TAGS = "QUERY_REPO_TAGS";
export const QUERY_REPO_TAGS_SUCCESS = "QUERY_REPO_TAGS_SUCCESS";
export const QUERY_REPO_TAGS_FAIL = "QUERY_REPO_TAGS_FAIL";

export const QUERY_REPO_CATEGORIES = "QUERY_REPO_CATEGORIES";
export const QUERY_REPO_CATEGORIES_SUCCESS = "QUERY_REPO_CATEGORIES_SUCCESS";
export const QUERY_REPO_CATEGORIES_FAIL = "QUERY_REPO_CATEGORIES_FAIL";

export const QUERY_REPO_OWNER = "QUERY_REPO_OWNER";
export const QUERY_REPO_OWNER_SUCCESS = "QUERY_REPO_OWNER_SUCCESS";
export const QUERY_REPO_OWNER_FAIL = "QUERY_REPO_OWNER_FAIL";

export const QUERY_REPO_CONTRIBUTORS = "QUERY_REPO_CONTRIBUTORS";
export const QUERY_REPO_CONTRIBUTORS_SUCCESS = "QUERY_REPO_CONTRIBUTORS_SUCCESS";
export const QUERY_REPO_CONTRIBUTORS_FAIL = "QUERY_REPO_CONTRIBUTORS_FAIL";

export const FETCH_REPO_README = "FETCH_REPO_README";
export const FETCH_REPO_README_SUCCESS = "FETCH_REPO_README_SUCCESS";
export const FETCH_REPO_README_FAIL = "FETCH_REPO_README_FAIL";

export const FETCH_REPO_CONTRIBUTORS = "FETCH_REPO_CONTRIBUTORS";
export const FETCH_REPO_CONTRIBUTORS_SUCCESS = "FETCH_REPO_CONTRIBUTORS_SUCCESS";
export const FETCH_REPO_CONTRIBUTORS_FAIL = "FETCH_REPO_CONTRIBUTORS_FAIL";

export const UPDATE_SELECTED_REPO = "UPDATE_SELECTED_REPO";
export const UPDATE_SELECTED_REPO_SUCCESS = "UPDATE_SELECTED_REPO_SUCCESS";
export const UPDATE_SELECTED_REPO_FAIL = "UPDATE_SELECTED_REPO_FAIL";

export const UPDATE_REPO_NOTE = "UPDATE_REPO_NOTE";
export const UPDATE_REPO_NOTE_SUCCESS = "UPDATE_REPO_NOTE_SUCCESS";
export const UPDATE_REPO_NOTE_FAIL = "UPDATE_REPO_NOTE_FAIL";

export const UPDATE_REPO_CATEGORIES = "UPDATE_REPO_CATEGORIES";
export const UPDATE_REPO_CATEGORIES_SUCCESS = "UPDATE_REPO_CATEGORIES_SUCCESS";
export const UPDATE_REPO_CATEGORIES_FAIL = "UPDATE_REPO_CATEGORIES_FAIL";

export const UPDATE_REPO_CONTRIBUTORS = "UPDATE_REPO_CONTRIBUTORS";
export const UPDATE_REPO_CONTRIBUTORS_SUCCESS = "UPDATE_REPO_CONTRIBUTORS_SUCCESS";
export const UPDATE_REPO_CONTRIBUTORS_FAIL = "UPDATE_REPO_CONTRIBUTORS_FAIL";
