// debug

export const DEBUG = process.env.NODE_ENV === 'development'

// accounts

export const GET_LOCAL_CREDENTIALS = 'GET_LOCAL_CREDENTIALS'
export const GET_LOCAL_CREDENTIALS_SUCCESS = 'GET_LOCAL_CREDENTIALS_SUCCESS'
export const GET_LOCAL_CREDENTIALS_FAIL = 'GET_LOCAL_CREDENTIALS_FAIL'

export const CLEAR_LOGIN_USERNAME = 'CLEAR_LOGIN_USERNAME'
export const CLEAR_LOGIN_PASSWORD = 'CLEAR_LOGIN_PASSWORD'

export const CHANGE_LOGIN_USERNAME = 'CHANGE_LOGIN_USERNAME'
export const CHANGE_LOGIN_PASSWORD = 'CHANGE_LOGIN_PASSWORD'

export const REQUEST_LOGIN = 'REQUEST_LOGIN'
export const REQUEST_LOGIN_SUCCESS = 'REQUEST_LOGIN_SUCCESS'
export const REQUEST_LOGIN_FAIL = 'REQUEST_LOGIN_FAIL'

// localStorage key

export const LOCAL_STORAGE_USERNAME_KEY = 'sc_username'
export const LOCAL_STORAGE_USER_PROFILE = 'sc_profile'

// app network

export const APP_OFFLINE = 'APP_OFFLINE'
export const APP_ONLINE = 'APP_ONLINE'

// database
export const DB_CONNECTED = 'DB_CONNECTED'
export const DB_DISCONNECTED = 'DB_DISCONNECTED'
export const DB_CONNECTION_CHANGE = 'DB_CONNECTION_CHANGE'

export const DB_COLLECTION_CHANGE = 'DB_COLLECTION_CHANGE' // include doc insert/update/delete.. of docs on this collection
export const DB_DOCUMENT_INSERT = 'DB_DOCUMENT_INSERT'
export const DB_DOCUMENT_DELETE = 'DB_DOCUMENT_DELETE'
export const DB_DOCUMENT_UPDATE = 'DB_DOCUMENT_UPDATE'

// real-time repos lists
export const UPDATE_REPOS_LIST = 'UPDATE_REPOS_LIST'
export const UPDATE_REPOS_LIST_SUCCESS = 'UPDATE_REPOS_LIST_SUCCESS'
export const UPDATE_REPOS_LIST_FAIL = 'UPDATE_REPOS_LIST_FAIL'

// search/order/filter/category
export const UPDATE_SEARCH_CONDITION = 'UPDATE_SEARCH_CONDITION'
export const UPDATE_ORDER_CONDITION = 'UPDATE_ORDER_CONDITION'
export const UPDATE_FILTER_CONDITION = 'UPDATE_FILTER_CONDITION'
export const UPDATE_CATEGORY_CONDITION = 'UPDATE_CATEGORY_CONDITION'

// search field
export const SEARCH_FIELD_ALL = 'SEARCH_FIELD_ALL'
export const SEARCH_FIELD_REPO_NAME = 'SEARCH_FIELD_REPO_NAME'
export const SEARCH_FIELD_REPO_DESCRIPTION = 'SEARCH_FIELD_REPO_DESCRIPTION'
export const SEARCH_FIELD_REPO_REMARK = 'SEARCH_FIELD_REPO_REMARK'

// filter types
export const FILTER_TYPE_NONE = 'FILTER_TYPE_NONE'
export const FILTER_TYPE_FLAG = 'FILTER_TYPE_FLAG'
export const FILTER_TYPE_REMAKR = 'FILTER_TYPE_REMAKR'
export const FILTER_TYPE_UNREAD = 'FILTER_TYPE_UNREAD'


// order types
export const ORDER_BY_DEFAULT = 'ORDER_BY_DEFAULT'
export const ORDER_BY_STARS_COUNT = 'ORDER_BY_STARS_COUNT'
export const ORDER_BY_FORKS_COUNT = 'ORDER_BY_FORKS_COUNT'
export const ORDER_BY_WATCHERS_COUNT = 'ORDER_BY_WATCHERS_COUNT'
export const ORDER_BY_OPEN_ISSUES_COUNT = 'ORDER_BY_OPEN_ISSUES_COUNT'
export const ORDER_BY_SIZE
export const SORT_TYPE_
export const SORT_TYPE_
export const SORT_TYPE_