// debug

export const DEBUG = process.env.NODE_ENV === 'development'

// accounts

export const GET_LOCAL_CREDENTIALS = 'GET_LOCAL_CREDENTIALS'
export const GET_LOCAL_CREDENTIALS_SUCCESS = 'GET_LOCAL_CREDENTIALS_SUCCESS'
export const GET_LOCAL_CREDENTIALS_FAIL = 'GET_LOCAL_CREDENTIALS_FAIL'

export const CLEAR_LOGIN_USERNAME = 'CLEAR_LOGIN_USERNAME'
export const CLEAR_LOGIN_PASSWORD = 'CLEAR_LOGIN_PASSWORD'

export const CHANGE_LOGIN_USERNAME = 'CHANGE_LOGIN_USERNAME'
export const CHANGE_LOGIN_PASSWORD = 'CHANGE_LOGIN_PASSWORD'

export const REQUEST_LOGIN = 'REQUEST_LOGIN'
export const REQUEST_LOGIN_SUCCESS = 'REQUEST_LOGIN_SUCCESS'
export const REQUEST_LOGIN_FAIL = 'REQUEST_LOGIN_FAIL'

// localStorage key

export const LOCAL_STORAGE_USERNAME_KEY = 'sc_username'
export const LOCAL_STORAGE_USER_PROFILE = 'sc_profile'

// app network

export const APP_OFFLINE = 'APP_OFFLINE'
export const APP_ONLINE = 'APP_ONLINE'
