// accounts

export const GET_LOCAL_CREDENTIALS = 'GET_LOCAL_CREDENTIALS'
export const CLEAR_LOGIN_USERNAME = 'CLEAR_LOGIN_USERNAME'
export const CLEAR_LOGIN_PASSWORD = 'CLEAR_LOGIN_PASSWORD'
export const CHANGE_LOGIN_USERNAME = 'CHANGE_LOGIN_USERNAME'
export const CHANGE_LOGIN_PASSWORD = 'CHANGE_LOGIN_PASSWORD'
export const REQUEST_LOGIN = 'REQUEST_LOGIN'

// debug

export const DEBUG = process.env.NODE_ENV === 'development'
