// filter types
enum FilterType {
    FILTER_OPTION_NONE = "FILTER_OPTION_NONE",
    FILTER_OPTION_HAS_FLAG = "FILTER_OPTION_HAS_FLAG",
    FILTER_OPTION_HAS_NOTE = "FILTER_OPTION_HAS_NOTE",
    FILTER_OPTION_UNREAD = "FILTER_OPTION_UNREAD"
}

export default FilterType;
