// search field

enum SearchType {
    SEARCH_FIELD_ALL = "SEARCH_FIELD_ALL",
    SEARCH_FIELD_REPO_NAME = "SEARCH_FIELD_REPO_NAME",
    SEARCH_FIELD_REPO_DESCRIPTION = "SEARCH_FIELD_REPO_DESCRIPTION",
    SEARCH_FIELD_REPO_NOTE = "SEARCH_FIELD_REPO_NOTE",
    SEARCH_FIELD_REPO_TAGS = "SEARCH_FIELD_REPO_TAGS"
}

export default SearchType;
