// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/b299105c8115935e9850b535c56dd78c2bef4ce5/webpack-hot-middleware/index.d.ts
declare module 'webpack-hot-middleware' {
// Type definitions for webpack-hot-middleware 2.15
// Project: https://github.com/glenjamin/webpack-hot-middleware#readme
// Definitions by: Benjamin Lim <https://github.com/bumbleblym>
// Definitions: https://github.com/DefinitelyTyped/DefinitelyTyped

import { NextHandleFunction } from 'connect';
import { compiler } from 'webpack';

export = WebpackHotMiddleware;

function WebpackHotMiddleware(
	compiler: compiler.Compiler,
	options?: WebpackHotMiddleware.Options
): NextHandleFunction;

namespace WebpackHotMiddleware {
	interface Options {
		log?: false | Logger;
		path?: string;
		heartbeat?: number;
	}

	type Logger = (message?: any, ...optionalParams: any[]) => void;
}
}
