export const CLOSE_LOGIN = "CLOSE_LOGIN";

export const SAVE_CREDENTIALS_TO_SYSTEM = "SAVE_CREDENTIALS_TO_SYSTEM";
export const SAVE_CREDENTIALS_TO_SYSTEM_REPLY =
    "SAVE_CREDENTIALS_TO_SYSTEM_REPLY";

export const GET_LOCAL_CREDENTIALS = "GET_LOCAL_CREDENTIALS";
export const GET_LOCAL_CREDENTIALS_REPLY = "GET_LOCAL_CREDENTIALS_REPLY";

export const DELETE_LOCAL_CREDENTIALS = "DELETE_LOCAL_CREDENTIALS";
export const DELETE_LOCAL_CREDENTIALS_REPLY = "DELETE_LOCAL_CREDENTIALS_REPLY";

export const SHOW_MAIN_WIN_AND_CLOSE_LOGIN_WIN =
    "SHOW_MAIN_WIN_AND_CLOSE_LOGIN_WIN";

export const OPEN_SETTING_WIN = "OPEN_SETTING_WIN";
export const CLOSE_SETTING_WIN = "CLOSE_SETTING_WIN";

export const SHOW_CHOOSE_DIRECTORY_DIALOG = "SHOW_CHOOSE_DIRECTORY_DIALOG";
export const SHOW_CHOOSE_DIRECTORY_DIALOG_REPLG =
    "SHOW_CHOOSE_DIRECTORY_DIALOG_REPLG"; // return the path to save json file
export const SHOW_CHOOSE_FILE_DIALOG = "SHOW_CHOOSE_FILE_DIALOG";
// export const SHOW_CHOOSE_FILE_DIALOG_REPLY = 'SHOW_CHOOSE_FILE_DIALOG_REPLY'
export const READ_FILE_FAILED = "READ_FILE_FAILED";

export const EXPORT_STARS_DATA = "EXPORT_STARS_DATA";
export const EXPORT_STARS_DATA_SUCCESS_REPLY =
    "EXPORT_STARS_DATA_SUCCESS_REPLY";
export const EXPORT_STARS_DATA_FAIL_REPLY = "EXPORT_STARS_DATA_FAIL_REPLY";

export const SENT_IMPORT_STARS_DATA = "SENT_IMPORT_STARS_DATA";

export const RESTART_APP = "RESTART_APP";
export const QUIT_APP = "QUIT_APP";
