export const CLOSE_LOGIN = 'CLOSE_LOGIN'

export const SAVE_CREDENTIALS_TO_SYSTEM = 'SAVE_CREDENTIALS_TO_SYSTEM'
export const SAVE_CREDENTIALS_TO_SYSTEM_REPLY = 'SAVE_CREDENTIALS_TO_SYSTEM_REPLY'

export const GET_LOCAL_CREDENTIALS = 'GET_LOCAL_CREDENTIALS'
export const GET_LOCAL_CREDENTIALS_REPLY = 'GET_LOCAL_CREDENTIALS_REPLY'
