export const CLOSE_LOGIN = 'CLOSE_LOGIN'

export const SAVE_CREDENTIALS_TO_SYSTEM = 'SAVE_CREDENTIALS_TO_SYSTEM'
export const SAVE_CREDENTIALS_TO_SYSTEM_REPLY = 'SAVE_CREDENTIALS_TO_SYSTEM_REPLY'

export const GET_LOCAL_CREDENTIALS = 'GET_LOCAL_CREDENTIALS'
export const GET_LOCAL_CREDENTIALS_REPLY = 'GET_LOCAL_CREDENTIALS_REPLY'

export const DELETE_LOCAL_CREDENTIALS = 'DELETE_LOCAL_CREDENTIALS'
export const DELETE_LOCAL_CREDENTIALS_REPLY = 'DELETE_LOCAL_CREDENTIALS_REPLY'

export const SHOW_MAIN_WIN_AND_CLOSE_LOGIN_WIN = 'SHOW_MAIN_WIN_AND_CLOSE_LOGIN_WIN'

export const OPEN_SETTING_WIN = 'OPEN_SETTING_WIN'
export const CLOSE_SETTING_WIN = 'CLOSE_SETTING_WIN'
